Move la clearing to trigger so we don't need that very ugly patch in dpkg for it

diff --git a/fink.info.in b/fink.info.in
--- a/fink.info.in
+++ b/fink.info.in
@@ -2,9 +2,12 @@ Package: fink
 Version: @VERSION@
 Revision: @REVISION@
 Distribution: @DISTRIBUTION@
-Depends: base-files
+Depends: <<
+	dpkg (>> 1.16) || dpkg-bootstrap (>> 1.16),
+	base-files
+<<
 Recommends: <<
- apt (>= 0.5.4-41)
+	apt (>= 0.5.4-41)
 <<
 Conflicts: gcc3.1 (= 1175-6)
 Replaces: gcc3.1 (= 1175-6)
@@ -14,46 +17,71 @@ Source-MD5: @MD5@
 NoSetPATH: true
 BuildAsNobody: false
 CompileScript: <<
- ./pre-build-test.sh
- make test PREFIX=%p ARCHITECTURE=%m DISTRIBUTION=@DISTRIBUTION@
- ./setup.sh %p %m
+./pre-build-test.sh
+make test PREFIX=%p ARCHITECTURE=%m DISTRIBUTION=@DISTRIBUTION@
+./setup.sh %p %m
 <<
 InstallScript: <<
- ./install.sh %i %m
- install -c -p -m 644 fink.shlibs "%d/DEBIAN/shlibs"
+./install.sh %i %m
+install -c -p -m 644 fink.shlibs "%d/DEBIAN/shlibs"
+<<
+Triggers: <<
+	Interest-noawait: <<
+		%p/lib
+	<<
 <<
 PostInstScript: <<
- %p/lib/fink/postinstall.pl %m
- %p/bin/fink --no-use-binary-dist index
+# dpkg triggers to clean .la files (we can not get a pkg name to process all)
+if [ "$1" = "triggered" ]; then
+		msg="Clearing dependency_libs of .la files"
+		for lafile in `find %p/lib -name *.la`; do
+			if [ -f "$lafile" ] && [ ! -h "$lafile" ]; then
+				if [ -n "$msg" ]; then
+					echo $msg
+					msg=""
+				fi
+				perl -pi -e "s/^(dependency_libs)=.*/\1=''/" "$lafile" || true
+			fi
+		done
+	fi
+	exit 0
+fi
 
- # try to clean up left-overs from previous versions (old location)
- rm -f %p/var/db/fink.db
- rm -f %p/var/db/shlibs.db
- rm -f %p/var/lib/fink/fink.db
+%p/lib/fink/postinstall.pl %m
+%p/bin/fink --no-use-binary-dist index
+
+# try to clean up left-overs from previous versions (old location)
+rm -f %p/var/db/fink.db
+rm -f %p/var/db/shlibs.db
+rm -f %p/var/lib/fink/fink.db
 <<
 PreRmScript: <<
- # clean up package indexes
- [ \! -d %p/var/lib/fink/finkinfodb ] || touch %p/var/lib/fink/finkinfodb/invalidate
- rm -f %p/var/lib/fink/index.db
- rm -f %p/var/lib/fink/index.db.lock
- rm -f %p/var/lib/fink/infolist
- rm -f %p/var/lib/fink/shlibs.db
- rm -f %p/var/lib/fink/shlibs.db.lock
+if [ "$1" = "triggered" ]; then
+    exit 0
+fi
+
+# clean up package indexes
+[ \! -d %p/var/lib/fink/finkinfodb ] || touch %p/var/lib/fink/finkinfodb/invalidate
+rm -f %p/var/lib/fink/index.db
+rm -f %p/var/lib/fink/index.db.lock
+rm -f %p/var/lib/fink/infolist
+rm -f %p/var/lib/fink/shlibs.db
+rm -f %p/var/lib/fink/shlibs.db.lock
 <<
 #
 Description: Open-source software package manager
 DescPackaging: <<
- Don't use mirror:sourceforge so that older package manager versions
- which do not know that mirror can still selfupdate.
+Don't use mirror:sourceforge so that older package manager versions
+which do not know that mirror can still selfupdate.
 
- Must put "make test" before "./setup.sh %p %m", because make test runs
- the setup script itself, but pointed at the testing directory.
- The second run of setup.sh properly points fink at the installed
- configuration file.
+Must put "make test" before "./setup.sh %p %m", because make test runs
+the setup script itself, but pointed at the testing directory.
+The second run of setup.sh properly points fink at the installed
+configuration file.
 
- We are using Conflicts/Replaces against gcc3.1 so that the Fink gcc3.1 
- package is removed (in favor of an Apple-supplied gcc 3.1, represented
- by a virtual package).
+We are using Conflicts/Replaces against gcc3.1 so that the Fink gcc3.1 
+package is removed (in favor of an Apple-supplied gcc 3.1, represented
+by a virtual package).
 <<
 DescDetail: <<
 fink is the Fink project's package manager. It is responsible for
